from _collections import deque

l = deque([])
l.append(10)
print(list(l))
l.append(100)
print(list(l))
l.append(1000)
print(list(l))
l.append(10000)
print(list(l))
l.append(100000)
print(list(l))
l.popleft()
print(list(l))
l.popleft()
print(list(l))
l.popleft()
print(list(l))
l.popleft()
print(list(l))